
name: Deploy to Backend to Prod Env

# Github Action for deploying an application to an EC2 instance directly using SSH.
# This workflow automates the deployment process to your EC2 instance running Ubuntu.
# It assumes that you have already set up your EC2 instance, SSH key pair, and GitHub Secrets.
# Define AWS credentials as GitHub Secrets: AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY

# Environment Variables Needed:
# - AWS_ACCESS_KEY_ID: Your AWS access key ID
# - AWS_SECRET_ACCESS_KEY: Your AWS secret access key
# - SSH_PRIVATE_KEY: Your SSH private key used for authentication with the EC2 instance
# - SSH_HOST: The hostname or IP address of your EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy_web_app:
    runs-on: ubuntu-latest
    environment: Prod
    strategy:
      matrix:
        max-parallel: [2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Add public IP to AWS security group for Web App
        uses: sohelamin/aws-security-group-add-ip-action@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          aws-security-group-id: 'sg-004bae2ed02dd0ab7'
          port: '22'
          to-port: '22'
          protocol: 'tcp'
          description: 'GitHub Action'

      - name: Configure SSH for Web App
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" > ~/.ssh/config

      - name: Deploy code to Web App
        run: |
          ssh ubuntu@${{ secrets.SSH_HOST }} "cd /home/ubuntu/test-frontend && git stash && git pull && npm install && npm run build && pm2 restart 0"
      - name: Deployment complete
        run: |
           echo "------------------------------------"
           echo "|                                  |"
           echo "|       🚀 Deployment Complete      |"
           echo "|                                  |"
           echo "------------------------------------"
